.github/workflows/android_kit_pull_request.yml
- check dependabot PR target branch
- Check Android Kit Dependabot PR jobs for success/fail
=> fix: also check dependabot PR target branch

.github/workflows/sdk-release-repo-branch-check.yml
- allow releases to happen on main branch
- Run a release job from main branch
=> fix: allow releases to happen on main branch

.github/workflows/sdk-release-repo-branch-check.yml
- bugfix github _ref
- test release job on main branch
=> fix: bugfix github_ref

.github/workflows/sdk-release-repo-branch-check.yml
- Update conditional
- Test release job on main branch
=> fix: conditional

.github/workflows/sdk-release-repo-branch-check.yml
- 2nd attempt at conditional fix
- Test release with main branch
=> fix: conditional 2nd attempt

.github/workflows/android-kit-daily.yml
- Fix daily android kit cron token
- run workflow version of job on a kit
=> ci: change token for android kit daily cron

.github/workflows/daily-cron.yml
- Add in token param for Android kit daily workflow call
- kit daily cron should work
=> ci: test workflow call token

.github/workflows/android-kit-pull-request.yml
Add Lint job for Android Kits
additional check, PR check will fail if linting fails
=> feat: Add Lint job for Android Kits

.github/workflows/android-kit-pull-request.yml, .github/workflows/android-kit-push.yml
fix typos from the last PR
existing tests pass
=> fix: typo introduced in previous commit

.github/workflows/android-kit-pull-request.yml, .github/workflows/android-kit-push.yml
Fix a few inconsistencies and allow error's in Maven job's test steps
existing tests pass
=> feat: Fix a few inconsistencies and allow error's in Maven job's test steps

.github/workflows/android-kit-pull-request.yml, .github/workflows/pr-branch-target-continuous.yml, .github/workflows/pr-branch-target-gitflow.yml
allow "build/" branches in continuous-style repositories
- add reporting that will print branch name in logs
tested in adjust-kit repo
=> feat: allow build/ target branches

.github/workflows/android-sample-app-pull-request.yml
- Fix pull request warnings in android sample apps repo
- Test CI in android sample apps repo
- Closes https://go.mparticle.com/work/77398
=> fix: clean up pull request warnings in android sample apps repo

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/android-sample-app-push.yml
- separate out push/pull request actions for sample apps
- test CI from sample app repos
- Closes https://go.mparticle.com/work/77398
=> fix: separate out push/pull request actions for sample apps

.github/workflows/pr-branch-check-name.yml, .github/workflows/pr-title-check.yml
- Add additional logging for branch, title check. Print current value and list possible values for failures
- Tested manually on Unity repo
- Closes https://go.mparticle.com/work/SQDSDKS-3623
=> fix: add additional logging for branch, title check

.github/workflows/android-sample-app-pull-request.yml, .github/workflows/android-sample-app-push.yml, .github/workflows/dependabot-rebase-development.yml, .github/workflows/dependabot-rebase-main.yml
- Add in dependabot rebase jobs
- Try calling dependabot job from child repo
- Closes https://go.mparticle.com/work/SQDSDKS-3633
=> feat: add in dependabot rebase jobs

.github/workflows/data-plan-fetch.yml
- Add reusable workflow for fetching data plans
Closes https://go.mparticle.com/work/SQDSDKS-3973
=> ci: add workflow for fetching data plans

.github/workflows/pr-branch-check-name.yml, .github/workflows/pr-branch-target-continuous.yml, .github/workflows/pr-branch-target-gitflow.yml, .github/workflows/pr-title-check.yml
- Add in dependabot branch support
- Make sure this change doesn't break normal pull requests
- Closes https://go.mparticle.com/work/SQDSDKS-4141
=> feat: add in dependabot

.github/workflows/android-kit-pull-request.yml
- update branch dependencies
- test android kit dependabot job (e.g. adobe)
- Closes https://go.mparticle.com/work/SQDSDKS-4219
=> fix: update branch dependencies

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/android-kit-pull-request.yml, .github/workflows/android-kit-push.yml, .github/workflows/pr-branch-check-name.yml, .github/workflows/pr-branch-target-continuous.yml, .github/workflows/pr-branch-target-gitflow.yml, .github/workflows/pr-title-check.yml
- Update gradle and ubuntu versions in mparticle-workflows repo
- Regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4548
=> feat: Update gradle and ubuntu versions in mparticle-workflows repo

.github/workflows/issue-to-jira-ticket.yml
- Add ability to call jira github actions from child repos
-  Tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4561
=> ci: Update issue-to-jira-ticket.yml

.github/workflows/issue-comment-to-jira.yml, .github/workflows/issue-status-update-from-jira.yml
- Add ability to call jira github actions from child repos
-  Tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4561
=> ci: add workflow call 

.github/workflows/issue-status-update-from-jira.yml
Add missing open status, and fix ice box status.
Add missing open status, and fix ice box status.
Github workflow, will test once merged.
- Closes https://go.mparticle.com/work/SQDSDKS-4563
=> ci: add missing status, and fix typo

.github/workflows/issue-to-jira-ticket.yml
- Add step to comment on newly created issue
- {explain how this has been tested, and what additional testing should be done}
- Closes https://go.mparticle.com/work/SQDSDKS-4561
=> ci: Add issue comment after creation

.github/workflows/android-kit-pull-request.yml, .github/workflows/android-kit-push.yml, .github/workflows/data-plan-fetch.yml, .github/workflows/dependabot-automerge.yml, .github/workflows/dependabot-rebase-development.yml, .github/workflows/dependabot-rebase-main.yml, .github/workflows/issue-comment-to-jira.yml, .github/workflows/sdk-release-repo-branch-check.yml
- Update deprecate github actions
- Regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4658
=> ci: Update deprecate github actions

.github/workflows/dependabot-automerge.yml
- Dependabot automerge actions link
- Regression tests should pass.
- Closes https://go.mparticle.com/work/SQDSDKS-4693
=> fix: Dependabot automerge actions link

.github/workflows/dependabot-automerge.yml
- Dependabot automerge actions links for pull request merge
- All regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4693
=> fix: Dependabot automerge actions links for pull request merge

.github/workflows/dependabot-save-pr-number.yml, .github/workflows/sonarcloud.yml, .gitignore
- Add in dependabot save pr number and sonarcloud actions
- Regression tests should pass
- Save PR action run: https://github.com/mParticle/mparticle-android-media-sdk/actions/runs/3323609458
- Closes https://go.mparticle.com/work/SQDSDKS-4964
=> ci: Add in dependabot save pr number and sonarcloud actions

.github/workflows/daily-cron.yml
- Switch semgrep configs to just auto-detect for daily cron runs
- Will test within GH (as I can't test locally on my M1)
=> fix: Switch granular configs to auto

.github/workflows/web-run-test.yml
- Adds setup for Web Tests that can be reused
- N/A
- Closes https://go.mparticle.com/work/SQDSDKS-5364
=> ci: Introduce reusable Web test runner

.github/workflows/ios-kit-release.yml
- Added a new reusable workflow to release iOS kits.
- Tested manually on Github
- Closes https://go.mparticle.com/work/SQDSDKS-5486
=> ci: Add iOS Kit Release Workflow

.github/workflows/web-kit-pull-request.yml
- Renames incorrect step name
- N/A
- Closes https://go.mparticle.com/work/REPLACEME
=> fix: Rename PR workflow step
